PSDB/urls.py
from os import path
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shedule/', include('shedule.urls')),
    url(r'^archive/', include('archive.urls')),

]
#path.join(path.dirname(path.dirname(path.abspath(__file__))), 'static/')

shedule/urls.py
from django.conf.urls import url
from . import views

app_name = 'shedule'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login/$', views.enter, name = 'login'),
    url(r'^exit/$', views.exit, name = 'logout'),
    url(r'^(?P<day>[0-9]+)/$', views.shedule, name='shedule'),
    url(r'^(?P<day>[0-9]+)/(?P<pk>[0-9]+)/$', views.lesson, name='lesson'),
    url(r'^(?P<day>[0-9]+)/(?P<pk>[0-9]+)/enroll/$', views.enroll, name='enroll'),
    url(r'^account/$', views.account, name='account'),
    url(r'^account/edit/$', views.edit, name='edit'),
]

shedule/models.py
from __future__ import unicode_literals
from datetime import timedelta
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image


class Watcher(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)

    name = models.CharField(max_length=30)
    bg = models.CharField(max_length=30, blank=True)
    photo = models.ImageField(upload_to='static/images/Watcher/',blank=True)
    info = models.TextField(blank=True)
    def __unicode__(self):
        return self.name
    class Meta:
        db_table = 'watchers'

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Watcher.objects.create(user=instance, name=instance.username)
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.watcher.save()

class LessonManager(models.Manager):
    def day_lessons(self, day):
        return self.filter(day=day)
    def day_list(self):
        return self.order_by('day').distinct('day').values_list('day')
    def fake_day_list(self):
        top_day = self.order_by('-day').first().day
        return range(1,top_day+1,1)
class Lesson(models.Model):
    name = models.CharField(max_length=50)
    max_students = models.IntegerField(default=12)
    place = models.CharField(max_length=50, choices=[ ])
    day = models.IntegerField(default=1)
    previous_lesson_day = models.IntegerField(default=0, blank=True)
    start_time = models.TimeField()
    short_info = models.TextField()
    teacher = models.ForeignKey(Watcher, related_name='teacher_lessons')
    students = models.ManyToManyField(Watcher,related_name='student_lessons', blank=True)
    is_specialization = models.BooleanField(default=False)
    def __unicode__(self):
        return self.name
    def get_absolute_url(self):
        return 'shedule/%d' % self.pk
    def get_short_count(self):
        return str(self.students.count()) + '/' + str(self.max_students)
    class Meta:
        db_table = 'lessons'
        ordering = ['-day']
    objects = LessonManager()

shedule/views.py
#! /usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, reverse
from .models import Lesson, Watcher
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login


def index(request):
    return HttpResponseRedirect(reverse('shedule:lesson', args=(1,0)))


def shedule(request, day):
    return HttpResponseRedirect(reverse('shedule:lesson', args=(1,0)))

def lesson (request, day, pk):
    day_list = Lesson.objects.fake_day_list()
    lesson_list = Lesson.objects.day_lessons(day)
    current_lesson = lesson_list.filter(pk=pk).first()
    context = {'lesson_list': lesson_list,
               'day_list': day_list,
               'user': request.user,
               'current_lesson': current_lesson,}
    return render(request, 'shedule/shedule.html', context)

def enroll(request, day,pk):
    lesson = get_object_or_404(Lesson, pk=pk)
    if (request.user.is_authenticated):
        watcher = request.user.watcher
        students = lesson.students.all()
        answer = (not students.filter(pk=watcher.pk))
        if (not answer):
            messages.error(request, 'Вы уже записаны на этот МК')
        else:
            answer = (students.count() < lesson.max_students)
            if (answer):
                previous_lesson = Lesson.objects.filter(name=lesson.name, day=lesson.previous_lesson_day)
                if (previous_lesson):
                    previous_student = previous_lesson.students.filter(pk=watcher.pk)
                    if (previous_student):
                        answer = False
                        messages.error(request, 'Вы не можете записаться на этот МК т.к. уже были на нем')
            else:
                messages.error(request, 'Все места уже заняты')
            if (answer):
                lesson.students.add(watcher)
                lesson.save()
                messages.success(request, "Готово! Вы записались на это занятие")
    else:
        messages.error(request, 'Войдите в систему, прежде чем записываться')
    return HttpResponseRedirect(reverse('shedule:lesson', args=(lesson.day, pk,)))

def exit(request):
    logout(request)
    return HttpResponseRedirect(reverse('shedule:login'))

def enter(request):
    if (not request.POST):
        return render(request, 'shedule/signin.html')
    else:
        username = request.POST['login']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('shedule:lesson', args=(1, 0)))
        else:
             messages.error(request, 'Неверный логин/пароль')
             return render(request, 'shedule/signin.html')

def account(request):
    context = {'watcher':request.user.watcher,
               'user' : request.user,}
    return render(request, 'shedule/account.html', context)
def edit(request):
    if (request.method == 'POST'):
        name = request.POST.get('name')
        bg = request.POST.get('bg')
        info = request.POST.get('info')
        watcher = request.user.watcher
        watcher.name = name
        watcher.bg = bg
        watcher.info = info
        watcher.save()
        return HttpResponseRedirect(reverse('shedule:account'))
    else:
        context = {'watcher': request.user.watcher,
                   'user': request.user, }
    return render(request, 'shedule/edit.html', context)

templates/shedule/account.html
{% extends 'base.html' %}

{% block title %}Аккаунт{% endblock %}

{% block sidemenu %}
    <ul class="nav nav-sidebar">
        <li><a href="#">Мои мастерклассы</a></li>
        <li><a href="#">Мои высадки</a></li>
        <li><a href="#">Мои баллы</a></li>
    </ul>
{% endblock %}

{% block content %}
    <div class="panel-heading">
        <h1 class="panel-title">{{ watcher.name }} <a class="btn btn-primary pull-right" href="edit/" role="button"><span class="glyphicon glyphicon-pencil"></span> Редактировать</a></h1>
    </div>

        <div class="row">
               <div class="col-xs-12 col-lg-4">
                  <img src="/{{ watcher.photo.url }}" class="img-thumbnail img-responsive" alt="Здесь могла быть ваша реклама"/>
               </div>
               <div class="col-xs-12 col-lg-8">
                  <p>Краткая информация:
                     <ul>
                        <li>Боевая группа: {{ watcher.bg }}</li>
                     </ul>
                  </p>
                  <p>{{ watcher.info }}</p>
               </div>
        </div>
{% endblock %}

templates/shedule/edit.html
{% extends 'base.html' %}

{% block title %}Редактирование{% endblock %}

{% block sidemenu %}
    <ul class="nav nav-sidebar">
        <li><a href="#">Мои мастерклассы</a></li>
        <li><a href="#">Мои высадки</a></li>
        <li><a href="#">Мои баллы</a></li>
    </ul>
{% endblock %}

{% block content %}
 <div class="panel-heading">
        <h1 class="panel-title">{{ watcher.name }} <a class="btn btn-primary pull-right" href="{% url 'shedule:account' %}" role="button"><span class="glyphicon glyphicon-pencil"></span> Отмена</a></h1>
    </div>

        <div class="row">
               <div class="col-xs-12 col-lg-4">
                  <img src="/{{ watcher.photo.url }}" class="img-thumbnail img-responsive" alt="Здесь могла быть ваша реклама"/>
               </div>
               <div class="col-xs-12 col-lg-8">
                 <form action="{% url 'shedule:edit' %}" method="post">
                     {% csrf_token %}
                       <input type="text" name = 'name' class="form-control" value="{{ watcher.name }}" >
                       <input type="text" name="bg" class="form-control" value="{{ watcher.bg }}">
                       <input type="text" name="info" class="form-control" value="{{ watcher.info }}">
                       <input class="btn btn-block btn-primary" type="submit" value="Изменить">
                 </form>
               </div>
        </div>
{% endblock %}

templates/shedule/shedule.html
{% extends 'base.html' %}

{% block title %}Расписание{% endblock %}

{% block sidemenu %}
    <ul class="nav nav-sidebar">
        {% for day in day_list %}
            <li><a href="{% url 'shedule:shedule' day %}">День {{ day }}</a></li>
        {% endfor %}
    </ul>
    <hr>
    {% if lesson_list %}
        <ul class="nav nav-sidebar">
            {% for lesson in lesson_list %}
                <li><a href="{% url 'shedule:lesson' lesson.day lesson.pk %}">{{ lesson.name }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

{% block content %}
    {% if current_lesson %}
        <div class="panel-heading">
            <h1 class="panel-title">{{ current_lesson.name }} <a class="btn btn-primary pull-right" href="#" role="button"><span class="glyphicon glyphicon-pencil"></span> Редактировать</a></h1>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-8 col-lg-10">
                    <ul>
                        <li>Ведет: { current_lesson.teacher.name }}</li>
                        <li>Место: {{ current_lesson.place }}</li>
                        <li>Время начала:{{ current_lesson.start_time }}</li>
                        <li>Занято мест: {{ current_lesson.get_short_count }}</li>
                    </ul>
                    <p>{{ current_lesson.short_info }}</p>
                </div>
                <div class="col-xs-4 col-lg-2">
                    <form action="{% url 'shedule:enroll' current_lesson.day current_lesson.pk %}" method="post">
                        {% csrf_token %}
                        <button type="submit" value="enroll" class="btn btn-primary" ><span class="glyphicon glyphicon-plus"></span> Записаться</button>
                    </form>
                </div>
                <div class="col-xs-12 col-lg-12">
                     {% if current_lesson.students.all %}
                        <div class="table-responsive">
                           <table class="table table-striped">
                              <thead>
                                 <tr>
                                    <th>Номер</th>
                                    <th>Имя</th>
                                    <th>БГ</th>
                                 </tr>
                              </thead>
                              <tbody>
                              {% for student in current_lesson.students.all %}
                                 <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ student.name }}</td>
                                        <td>{{ student.bg }}</td>
                                 </tr>
                              {% endfor %}
                              </tbody>
                           </table>
                        </div>
                     {% endif %}
                     {% if messages %}
                         {% for message in messages %}
                             <div
                                 {% if message.tags == 'error' %} class="alert alert-danger"
                                 {% elif message.tags == 'succes' %} class="alert alert-"
                                 {% endif %}>
                                              {{ message }}
                             </div>
                        {% endfor %}
                     {% endif %}
                        <p class="pull-left visible-xs">
                           <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Назад</button>
                        </p>
                     </div>
                  </div>
               </div>
            {% else %}
                {% if lesson_list %}
                      <ul class="nav nav-sidebar">
                         {% for lesson in lesson_list %}
                              <li><a href="{% url 'shedule:lesson' lesson.day lesson.pk %}">{{ lesson.name }}</a></li>
                         {% endfor %}
                      </ul>
                {% endif %}
     {% endif %}
{% endblock %}

templates/shedule/signin.html
 <!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=devise-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      {% load static %}
       <link href="{% static "style.css" %}" rel="stylesheet">
      <title>Вход</title>
   </head>
   <body>
      <div class="container signin">
         <form class="form-signin" action="{% url 'shedule:login' %}" method="post">
             {% csrf_token %}
         <h2 class="form-signin-heading">Войдите для использования архива</h2>
               <input type="text" name = 'login' class="form-control" placeholder="Логин" required autofocus>
               <input type="password" name="password" class="form-control" placeholder="Пароль" required>
               <input class="btn btn-block btn-primary" type="submit" value="Войти">
         </form>
      </div>
      {% if messages %}
                  <ul class="messages">
                      {% for message in messages %}
                          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                              {{ message }}
                          </li>
                      {% endfor %}
                  </ul>
      {% endif %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   </body>
</html>