PSDB/urls.py
from os import path
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^shedule/', include('shedule.urls')),
    url(r'^archive/', include('archive.urls')),

]
#path.join(path.dirname(path.dirname(path.abspath(__file__))), 'static/')

shedule/urls.py
from django.conf.urls import url
from . import views

app_name = 'shedule'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login/$', views.enter, name = 'login'),
    url(r'^exit/$', views.exit, name = 'logout'),
    url(r'^(?P<day>[0-9]+)/$', views.shedule, name='shedule'),
    url(r'^(?P<day>[0-9]+)/(?P<pk>[0-9]+)/$', views.lesson, name='lesson'),
    url(r'^(?P<day>[0-9]+)/(?P<pk>[0-9]+)/enroll/$', views.enroll, name='enroll'),
    url(r'^account/$', views.account, name='account'),
    url(r'^account/edit/$', views.edit, name='edit'),
]

templates/base.html
 <!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=devise-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
      {% load static %}
       <link href="{% static "style.css" %}" rel="stylesheet">
      <title>{% block title %}{% endblock %}</title>
   </head>
   <body>
      {% include 'header.html' %}

       <div class="row row-offcanvas row-offcanvas-left">
         <div class="col-xs-12 col-lg-3 sidebar-offcanvas">
            <div class="panel panel-info">
               <div class="panel-body">
                 {% block sidemenu %}{% endblock %}
               </div>
            </div>
         </div>
         <div class="col-xs-12 col-lg-9 main">
            <div class="panel panel-info">
                {% block  content %}{% endblock %}
            </div>
         </div>
       </div>

      {% include 'footer.html' %}

      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   </body>
</html>

templates/footer.html
<div class="navbar-inverse navbar-fixed-bottom">
    <div class="navbar-inner">
        <div class="container">
            Архив базы <b>Ц.У.Н.А.М.И.</b> ver 2.0<br>
            3583 год
        </div>
    </div>
</div>

templates/header.html
<nav class="navbar navbar-inverse navbar-fixed-top">
         <div class="container">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu-1" aria-expanded="false">
                  <span class="glyphicon glyphicon-menu-hamburger"></span>
               </button>
               <a href="main.html" class="navbar-brand"><span class="glyphicon glyphicon-eye-open"></span></a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-menu-1">
               <form class="navbar navbar-form navbar-left">
                  <div class="form-group">
                     <input type="text" name="search" placeholder="Поиск">
                  </div>
                  <div class="form-group">
                     <input type="submit" class="btn btn-primary" name="confirm" value="Ок">
                  </div>
               </form>
               <ul class="nav navbar-nav">
                   {% load menubuilder %}
                     {% menu main_menu %}
                     {% for menu in menuitems %}
                         <li><a href="{{ menu.url }}">{{ menu.title }}</a></li>
                     {% endfor %}
                     {% if user.is_authenticated%}
                         <li class="dropdown"><a href="{% url 'shedule:account' %}" class="dropdown-toggle" data-toggle="dropdown">Приветствую тебя, {{ user.watcher }} <span class="caret"></span></a>
                             <ul class="dropdown-menu" role="menu">
                                 {% menu dropdown_menu %}
                                {% for menu in menuitems %}
                                    <li><a href="{{ menu.url }}">{{ menu.title }}</a></li>
                                    {% if forloop == 1 %}
                                        <li class="divider"></li>
                                    {% endif %}
                             {% endfor %}
                             </ul>
                         </li>
                     {% else %}
                         <li><a href="{% url 'shedule:login' %}">Войти</a> </li>
                     {% endif %}
               </ul>
            </div>
         </div>
</nav>